[project]
name = "project"
version = "0.1.0"
description = ""
authors = [
    {name = "sam1000won", email = "sam1000won@github.com"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
